var gulp = require('gulp')
var tasks = require('./gulp/')

gulp.task('default', ['bower', 'assets', 'js', 'styles', 'php', 'watch'], tasks.BSync)
gulp.task('js', tasks.Javascript)
gulp.task('bower', tasks.Bower)
gulp.task('assets', tasks.Assets)
gulp.task('php', tasks.Php)
gulp.task('styles', tasks.Styles)
gulp.task('watch', tasks.Watch)
